# config.yaml
IMG0_PTH: "C:\\Users\\casab\\Downloads\\Rellis_3D_pylon_camera_node\\Rellis-3D\\00002\\pylon_camera_node\\frame001143-1581797264_709.jpg"
IMG1_PTH: "C:\\Users\\casab\\Downloads\\Rellis_3D_pylon_camera_node\\Rellis-3D\\00002\\pylon_camera_node\\frame001200-1581797270_409.jpg"
IMAGE_TYPE: "outdoor"
TEXT_PROMPT: "find all barriers in picture"
BOX_THRESHOLD: 0.35
TEXT_THRESHOLD: 0.25
LOFTR_INDOOR_PATH: "E:\\IMPACT\\scene_integration\\software_for_scenes\\LoFTR\\weights\\indoor_ds.ckpt"
LOFTR_OUTDOOR_PATH: "E:\\IMPACT\\scene_integration\\software_for_scenes\\LoFTR\\weights\\outdoor_ds.ckpt"
GDINO_SCRIPT: "E:\\IMPACT\\scene_integration\\software_for_scenes\\GroundingDINO\\groundingdino\\config\\GroundingDINO_SwinT_OGC.py"
GDINO_WEIGHTS: "E:\\IMPACT\\scene_integration\\software_for_scenes\\GroundingDINO\\weights\\groundingdino_swint_ogc.pth"
SAM_CHECKPOINT: "E:\\IMPACT\\scene_integration\\software_for_scenes\\sam2\\checkpoints\\sam2.1_hiera_large.pt"
SAM_MODEL_CFG: "E:\\IMPACT\\scene_integration\\software_for_scenes\\sam2\\sam2\\configs\\sam2.1\\sam2.1_hiera_l.yaml"
DISPLAY_POINTS_INSIDE: false
LOFTR_MATCHING_NAME: "LoFTR_matching"
RESIZE_HEIGHT: 480
RESIZE_WIDTH: 640


