# config.yaml

EXPERIMENT_NAME: "FSU_experiment_scenes"
TEXT_PROMPT: "brown scrubber"
IMG0_PTH: /home/cspooner/IMPACT1/data_collection/scene_integration/placement_data_20250602_141151/20250602_141151_Camera_-1_3_225.png
IMG1_PTH: /home/cspooner/IMPACT1/data_collection/scene_integration/placement_data_20250602_141151/20250602_141151_Camera_-1_3_180.png
LOFTR_IMAGE_TYPE: "indoor"

SAM_MODEL_ID: "facebook/sam3"
DISPLAY_POINTS_INSIDE: false
LOFTR_MATCHING_NAME: "LoFTR_matching"
RESIZE_HEIGHT: 480
RESIZE_WIDTH: 640
