# -*- coding: utf-8 -*-
"""LoFTR_demo_single_pair.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HETdsFEM27w5U7_jHhSnShblK7u0LvkK

# LoFTR demo with custom image pairs on Colab
We provide an easier way to run LoFTR with a custom image pair without configuring a python environment with GPU support. Signing in your Google account is required to run this notebook in Colab.

Start by clicking Runtime --> Run all (Ctrl/Cmd + F9).

Upload your own image pair with the "Choose Files" button to appear in the first cell. Please use horizontal images (width > height) and assign the image type (indoor/outdoor) accordingly.
"""

"""Our custom images"""



import torch
import cv2
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt
from typing import Tuple, List
import groundingdino.datasets.transforms as T

from software_for_scenes.LoFTR.src.utils.plotting import make_matching_figure
from software_for_scenes.LoFTR.src.loftr import LoFTR, default_cfg
from shapely.geometry import Point, Polygon
import geopandas as gpd

from torchvision.ops import box_convert
from groundingdino.util.inference import load_model, load_image, predict, annotate

from software_for_scenes.sam2.sam2.build_sam import build_sam2
from software_for_scenes.sam2.sam2.sam2_image_predictor import SAM2ImagePredictor
from PIL import Image





def show_mask(mask, ax, random_color=False, borders = True):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.6])], axis=0)
    else:
        color = np.array([30/255, 144/255, 255/255, 0.6])
    h, w = mask.shape[-2:]
    mask = mask.astype(np.uint8)
    mask_image =  mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    if borders:
        import cv2
        contours, _ = cv2.findContours(mask,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        # Try to smooth contours
        contours = [cv2.approxPolyDP(contour, epsilon=0.01, closed=True) for contour in contours]
        mask_image = cv2.drawContours(mask_image, contours, -1, (1, 1, 1, 0.5), thickness=2)
    ax.imshow(mask_image)

def show_points(coords, labels, ax, marker_size=375):
    pos_points = coords[labels==1]
    neg_points = coords[labels==0]
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)

def show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0, 0, 0, 0), lw=2))

def show_masks(image, masks, scores, point_coords=None, box_coords=None, input_labels=None, borders=True,randomColor=False):
    for i, (mask, score) in enumerate(zip(masks, scores)):
        plt.figure(figsize=(10, 10))
        plt.imshow(image)
        show_mask(mask, plt.gca(), borders=borders,random_color=randomColor)
        if point_coords is not None:
            assert input_labels is not None
            show_points(point_coords, input_labels, plt.gca())
        if box_coords is not None:
            # boxes
            show_box(box_coords, plt.gca())
        if len(scores) > 1:
            plt.title(f"Mask {i+1}, Score: {score:.3f}", fontsize=18)
        plt.axis('off')
        plt.show()

def load_image_fsu(image_path: str, w, h) -> Tuple[np.array, torch.Tensor]:
    transform = T.Compose(
        [
            T.RandomResize([800], max_size=1333),
            T.ToTensor(),
            T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ]
    )
    image_source = Image.open(image_path).convert("RGB")
    image_source = image_source.resize((w, h))
    image = np.asarray(image_source)
    image_transformed, _ = transform(image_source, None)
    return image, image_transformed


#import locale
#locale.getpreferredencoding = lambda: "UTF-8"

#### CONSTANTS ####

IMG0_PTH = "C:/Users/Gilbert/impact/20241211/20241211_141903.jpg"
IMG1_PTH = "C:/Users/Gilbert/impact/20241211/20241211_144244.jpg"
IMAGE_TYPE = 'outdoor'
TEXT_PROMPT = "blue ball"
BOX_TRESHOLD = 0.35
TEXT_TRESHOLD = 0.25
LOFTR_INDOOR_PATH = "software_for_scenes/LoFTR/weights/indoor_ds.ckpt"
LOFTR_OUTDOOR_PATH = "software_for_scenes/LoFTR/weights/outdoor_ds.ckpt"
GDINO_SCRIPT = "C:/Users/Gilbert/impact/software_for_scenes/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
GDINO_WEIGHTS = "C:/Users/Gilbert/impact/software_for_scenes/GroundingDINO/weights/groundingdino_swint_ogc.pth"
SAM_CHECKPOINT = "C:/Users/Gilbert/impact/software_for_scenes/sam2/checkpoints/sam2.1_hiera_large.pt"
SAM_MODEL_CFG = "C:/Users/Gilbert/impact/software_for_scenes/sam2/sam2/configs/sam2.1/sam2.1_hiera_l.yaml"
DISPLAY_POINTS_INSIDE = False
MATCHING_PATH_WHOLE = "LoFTR-colab-demo.pdf"
MATCHING_PATH_SHAPE = "LoFTR-colab-demo_2.pdf"
RESIZE_HEIGHT = 480
RESIZE_WIDTH = 640



image_pair = [IMG0_PTH, IMG1_PTH]



# The default config uses dual-softmax.
# The outdoor and indoor models share the same config.
# You can change the default values like thr and coarse_match_type.
matcher = LoFTR(config=default_cfg)
if IMAGE_TYPE == 'indoor':
  matcher.load_state_dict(torch.load(LOFTR_INDOOR_PATH)['state_dict'])
elif IMAGE_TYPE == 'outdoor':
  matcher.load_state_dict(torch.load(LOFTR_OUTDOOR_PATH)['state_dict'])
else:
  raise ValueError("Wrong image_type is given.")
matcher = matcher.eval().cuda()

# Rerun this cell (and below) if a new image pair is uploaded.
img0_raw = cv2.imread(image_pair[0], cv2.IMREAD_GRAYSCALE)
img0_bgr = cv2.imread(image_pair[0])
img0_rgb = cv2.cvtColor(img0_bgr, cv2.COLOR_BGR2RGB)
img0_rgb = cv2.resize(img0_rgb, (RESIZE_WIDTH, RESIZE_HEIGHT ))
img1_raw = cv2.imread(image_pair[1], cv2.IMREAD_GRAYSCALE)
img0_raw = cv2.resize(img0_raw, (RESIZE_WIDTH, RESIZE_HEIGHT))
img1_raw = cv2.resize(img1_raw, (RESIZE_WIDTH, RESIZE_HEIGHT))

img0 = torch.from_numpy(img0_raw)[None][None].cuda() / 255.
img1 = torch.from_numpy(img1_raw)[None][None].cuda() / 255.
batch = {'image0': img0, 'image1': img1}

# Inference with LoFTR and get prediction
with torch.no_grad():
    matcher(batch)
    mkpts0 = batch['mkpts0_f'].cpu().numpy()
    mkpts1 = batch['mkpts1_f'].cpu().numpy()
    mconf = batch['mconf'].cpu().numpy()

# Draw
color0 = cm.jet(mconf, alpha=0.7)
text0 = [
    'LoFTR',
    'Matches: {}'.format(len(mkpts0)),
]


# A high-res PDF will also be downloaded automatically.
make_matching_figure(img0_raw, img1_raw, mkpts0, mkpts1, color0, mkpts0, mkpts1, text0, path=MATCHING_PATH_WHOLE)


model = load_model(GDINO_SCRIPT,GDINO_WEIGHTS)


IMAGE_PATH = IMG0_PTH


image_source0, image0 = load_image_fsu(IMG0_PTH, RESIZE_WIDTH, RESIZE_HEIGHT)


boxes, logits, phrases = predict(
    model=model,
    image=image0,
    caption=TEXT_PROMPT,
    box_threshold=BOX_TRESHOLD,
    text_threshold=TEXT_TRESHOLD
)


predictor = SAM2ImagePredictor(build_sam2(SAM_MODEL_CFG, SAM_CHECKPOINT))
device = torch.device("cuda")

sam2_model = build_sam2(SAM_MODEL_CFG,SAM_CHECKPOINT, device=device)

predictor = SAM2ImagePredictor(sam2_model)

pil_image0 = Image.open(IMG0_PTH)
h, w, _ = image_source0.shape
pil_image0 = pil_image0.resize((w,h))
pil_image0 = np.array(pil_image0.convert("RGB"))
predictor.set_image(pil_image0)


boxes_cxcywh = boxes * torch.Tensor([w, h, w, h])
boxes_xyxy = box_convert(boxes=boxes_cxcywh, in_fmt="cxcywh", out_fmt="xyxy").numpy()
# uncomment if you want to see the annotated frames
#annotated_frame = annotate(image_source=image_source, boxes=boxes, logits=logits, phrases=phrases)

for box in boxes_xyxy:

  masks0, scores0, _ = predictor.predict(
    point_coords=None,
    point_labels=None,
    box=box[None,:],
    multimask_output=False,
  )

  show_masks(pil_image0, masks0, scores0,randomColor=True)

  flat_mask = masks0.flatten().reshape(h, w)

    
  contours, hierarchy = cv2.findContours(flat_mask.astype('uint8'), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
  shape_contours = contours[0].tolist()
  shape_contours = [x[0] for x in shape_contours]
  shape_contours_T= np.transpose(shape_contours)
  
 
  if  DISPLAY_POINTS_INSIDE:
    plt.imshow(img0_rgb)
    plt.scatter(mkpts0[:, 0], mkpts0[:, 1], marker="x", color="red", s=200)
    plt.scatter(shape_contours_T[0], shape_contours_T[1], marker=".", color="blue", s=200)
    plt.savefig("pointsnInside.jpg", dpi=300)
    plt.show()
  
  shape_poly = Polygon(shape_contours)
 
  picture0points = []
  picture1points=[]
  matchconf = []
  points1labels = []
  for index, points in enumerate(mkpts0):
    apoint = Point(points)

    if apoint.within(shape_poly):
        picture0points.append(mkpts0[index])
        picture1points.append(mkpts1[index])
        points1labels.append(1)
        matchconf.append(mconf[index])
  
  picture0points=np.array(picture0points)
  picture1points=np.array(picture1points)
  points1labels=np.array(points1labels)

  color1 = cm.jet(matchconf, alpha=0.7)
  text1 = [
    'LoFTR',
    'Matches: {}'.format(len(picture0points)),
]
  make_matching_figure(img0_raw, img1_raw, picture0points, picture1points, color1, picture0points, picture1points, text1, path=MATCHING_PATH_SHAPE)

  image_source1, image1 = load_image_fsu(IMG1_PTH, RESIZE_WIDTH, RESIZE_HEIGHT)
  h, w, _ = image_source1.shape
  pil_image1 = Image.open(IMG1_PTH)
  pil_image1 = pil_image1.resize((w,h))
  pil_image1 = np.array(pil_image1.convert("RGB"))  
  predictor.set_image(pil_image1)


  masks1, scores1, logits1 = predictor.predict(
    point_coords=picture1points,
    point_labels=points1labels,
    multimask_output=False,
  )

    
  show_masks(pil_image1, masks1, scores1,randomColor=True)
