# -*- coding: utf-8 -*-
"""LoFTR_demo_single_pair.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HETdsFEM27w5U7_jHhSnShblK7u0LvkK

# LoFTR demo with custom image pairs on Colab
We provide an easier way to run LoFTR with a custom image pair without configuring a python environment with GPU support. Signing in your Google account is required to run this notebook in Colab.

Start by clicking Runtime --> Run all (Ctrl/Cmd + F9).

Upload your own image pair with the "Choose Files" button to appear in the first cell. Please use horizontal images (width > height) and assign the image type (indoor/outdoor) accordingly.
"""

"""Our custom images"""



import torch
import cv2
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt

from software_for_scenes.LoFTR.src.utils.plotting import make_matching_figure
from software_for_scenes.LoFTR.src.loftr import LoFTR, default_cfg
#from shapely.geometry import Point, Polygon
import geopandas as gpd

from torchvision.ops import box_convert
from groundingdino.util.inference import load_model, load_image, predict, annotate

from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor
from PIL import Image




class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
 
# Checking if a point is inside a polygon
def point_in_polygon(point, polygon):
    num_vertices = len(polygon)
    x, y = point.x, point.y
    inside = False
 
    # Store the first point in the polygon and initialize the second point
    p1 = polygon[0]
 
    # Loop through each edge in the polygon
    for i in range(1, num_vertices + 1):
        # Get the next point in the polygon
        p2 = polygon[i % num_vertices]
 
        # Check if the point is above the minimum y coordinate of the edge
        if y > min(p1.y, p2.y):
            # Check if the point is below the maximum y coordinate of the edge
            if y <= max(p1.y, p2.y):
                # Check if the point is to the left of the maximum x coordinate of the edge
                if x <= max(p1.x, p2.x):
                    # Calculate the x-intersection of the line connecting the point to the edge
                    x_intersection = (y - p1.y) * (p2.x - p1.x) / (p2.y - p1.y) + p1.x
 
                    # Check if the point is on the same line as the edge or to the left of the x-intersection
                    if p1.x == p2.x or x <= x_intersection:
                        # Flip the inside flag
                        inside = not inside
 
        # Store the current point as the first point for the next iteration
        p1 = p2
 
    # Return the value of the inside flag
    return inside
    


def show_mask(mask, ax, random_color=False, borders = True):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.6])], axis=0)
    else:
        color = np.array([30/255, 144/255, 255/255, 0.6])
    h, w = mask.shape[-2:]
    mask = mask.astype(np.uint8)
    mask_image =  mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    if borders:
        import cv2
        contours, _ = cv2.findContours(mask,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        # Try to smooth contours
        contours = [cv2.approxPolyDP(contour, epsilon=0.01, closed=True) for contour in contours]
        mask_image = cv2.drawContours(mask_image, contours, -1, (1, 1, 1, 0.5), thickness=2)
    ax.imshow(mask_image)

def show_points(coords, labels, ax, marker_size=375):
    pos_points = coords[labels==1]
    neg_points = coords[labels==0]
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)

def show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0, 0, 0, 0), lw=2))

def show_masks(image, masks, scores, point_coords=None, box_coords=None, input_labels=None, borders=True):
    for i, (mask, score) in enumerate(zip(masks, scores)):
        plt.figure(figsize=(10, 10))
        plt.imshow(image)
        show_mask(mask, plt.gca(), borders=borders)
        if point_coords is not None:
            assert input_labels is not None
            show_points(point_coords, input_labels, plt.gca())
        if box_coords is not None:
            # boxes
            show_box(box_coords, plt.gca())
        if len(scores) > 1:
            plt.title(f"Mask {i+1}, Score: {score:.3f}", fontsize=18)
        plt.axis('off')
        plt.show()


#import locale
#locale.getpreferredencoding = lambda: "UTF-8"

img0_pth = "E:/IMPACT/data_collection/scene_integration/20241211/20241211_141903.jpg"
img1_pth = "E:/IMPACT/data_collection/scene_integration/20241211/20241211_144244.jpg"
image_pair = [img0_pth, img1_pth]



# The default config uses dual-softmax.
# The outdoor and indoor models share the same config.
# You can change the default values like thr and coarse_match_type.
image_type = 'outdoor'
matcher = LoFTR(config=default_cfg)
if image_type == 'indoor':
  matcher.load_state_dict(torch.load("software_for_scenes/LoFTR/weights/indoor_ds.ckpt")['state_dict'])
elif image_type == 'outdoor':
  matcher.load_state_dict(torch.load("software_for_scenes/LoFTR/weights/outdoor_ds.ckpt")['state_dict'])
else:
  raise ValueError("Wrong image_type is given.")
matcher = matcher.eval().cuda()

# Rerun this cell (and below) if a new image pair is uploaded.
img0_raw = cv2.imread(image_pair[0], cv2.IMREAD_GRAYSCALE)
img1_raw = cv2.imread(image_pair[1], cv2.IMREAD_GRAYSCALE)
img0_raw = cv2.resize(img0_raw, (640, 480))
img1_raw = cv2.resize(img1_raw, (640, 480))

img0 = torch.from_numpy(img0_raw)[None][None].cuda() / 255.
img1 = torch.from_numpy(img1_raw)[None][None].cuda() / 255.
batch = {'image0': img0, 'image1': img1}

# Inference with LoFTR and get prediction
with torch.no_grad():
    matcher(batch)
    mkpts0 = batch['mkpts0_f'].cpu().numpy()
    mkpts1 = batch['mkpts1_f'].cpu().numpy()
    mconf = batch['mconf'].cpu().numpy()

# Draw
color = cm.jet(mconf, alpha=0.7)
text = [
    'LoFTR',
    'Matches: {}'.format(len(mkpts0)),
]

plt.imshow(img0_raw)
plt.scatter(mkpts0[:, 0], mkpts0[:, 1], marker="x", color="red", s=200)
plt.show()

#fig = make_matching_figure(, img1_raw, mkpts0, mkpts1, color, mkpts0, mkpts1, text)

# A high-res PDF will also be downloaded automatically.
#make_matching_figure(img0_raw, img1_raw, mkpts0, mkpts1, color, mkpts0, mkpts1, text, path="LoFTR-colab-demo.pdf")



model = load_model("E:/IMPACT/scene_integration/software_for_scenes/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py", "E:/IMPACT/scene_integration/software_for_scenes/GroundingDINO/weights/groundingdino_swint_ogc.pth")

IMAGE_PATH = img0_pth
TEXT_PROMPT = "blue ball"
BOX_TRESHOLD = 0.35
TEXT_TRESHOLD = 0.25

image_source, image = load_image(IMAGE_PATH)

boxes, logits, phrases = predict(
    model=model,
    image=image,
    caption=TEXT_PROMPT,
    box_threshold=BOX_TRESHOLD,
    text_threshold=TEXT_TRESHOLD
)

checkpoint = "E:/IMPACT/scene_integration/software_for_scenes/sam2/checkpoints/sam2.1_hiera_large.pt"
model_cfg = "E:/IMPACT/scene_integration/software_for_scenes/sam2/sam2/configs/sam2.1/sam2.1_hiera_l.yaml"
predictor = SAM2ImagePredictor(build_sam2(model_cfg, checkpoint))
device = torch.device("cuda")

sam2_model = build_sam2(model_cfg,checkpoint, device=device)

predictor = SAM2ImagePredictor(sam2_model)

image = Image.open(img0_pth)
image = np.array(image.convert("RGB"))
predictor.set_image(image)

h, w, _ = image_source.shape
boxes_cxcywh = boxes * torch.Tensor([w, h, w, h])
boxes_xyxy = box_convert(boxes=boxes_cxcywh, in_fmt="cxcywh", out_fmt="xyxy").numpy()
# uncomment if you want to see the annotated frames
#annotated_frame = annotate(image_source=image_source, boxes=boxes, logits=logits, phrases=phrases)

for box in boxes_xyxy:

  masks, scores, _ = predictor.predict(
    point_coords=None,
    point_labels=None,
    box=box[None,:],
    multimask_output=False,
  )
  print(scores)
  print(box)
  print(masks)
  testmask = masks.flatten().reshape(h, w)
  print(testmask.shape)
  #plt.imshow(testmask)
  #plt.show()
  
  #ret, thresh = cv2.threshold(testmask, 127, 255, 0)
  
  contours, hierarchy = cv2.findContours(testmask.astype('uint8'), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
  blueballshape = contours[0].tolist()
  blueballshape = [x[0] for x in blueballshape]
  print(blueballshape)
  
  polygon = [Point(x, y) for x, y in blueballshape]
  print(polygon)
  
  
  #blueBall_poly = Polygon(blueballshape)
  #bluegpd = gpd.GeoSeries(blueBall_poly)
  #bluegpd.plot()
  #plt.show()
  count = 0
  for points in mkpts0:
    apoint = Point(points[0], points[1])
    print(apoint)
    if point_in_polygon(apoint, polygon):
        print("Point is inside the polygon")
    else:
        print("Point is outside the polygon")
    
    
  '''
  cv2.drawContours(image, contours, -1, (0, 255, 0), 4)
  
  cv2.imshow('Contours', image)
  cv2.waitKey(0)
  cv2.destroyAllWindows()
  '''
  
  #show_masks(image, masks, scores, box_coords=box)


#
#blueBall_poly
#blueBall_Contours = cv2.findContours(np.array(masks), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
#blueBall_Contours




#Trying to get contours from masks. That was provided by SAM. We will
#Polygon from the contours. Then will be able to check the matches to a point to
#See if they are inside the polygon and plot the ones that are acceptable.
