"""
LoFTR Scene Matching

This script demonstrates how to run the LoFTR matching algorithm on a pair of images,
followed by object detection (using GroundingDINO) and mask generation (using SAM2).
The configuration constants (such as file paths, thresholds, and image sizes) are
loaded from an external YAML file.

*NOTE:  LofTR works on grayscale images only

Before running, ensure that:
  - A 'loftr_config.yaml' file with the required settings exists in the same directory.
  - The necessary modules and dependencies are installed.
"""

import os
import cv2
import torch
import yaml
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt
from datetime import datetime
from PIL import Image
from typing import Tuple
import kornia as K
import kornia.feature as KF
import pycocotools.mask as mask_util
from matplotlib.patches import ConnectionPatch

# Import custom modules for transforms, plotting, and models
from kornia_moons.viz import draw_LAF_matches
from pathlib import Path
from shapely.geometry import Point, Polygon
from torchvision.ops import box_convert
#from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection

#from sam3.model_builder import build_sam3_image_model
#from sam3.model.sam3_image_processor import Sam3Processor
from transformers import Sam3Processor, Sam3Model

from huggingface_hub import login

hf_token = os.environ["HUGGINGFACE_HUB_TOKEN"]
login(hf_token)
# =============================================================================
# Helper Functions
# =============================================================================
def overlay_masks(image, masks):
    image = image.convert("RGBA")
    masks = 255 * masks.cpu().numpy().astype(np.uint8)
    
    n_masks = masks.shape[0]
    cmap = matplotlib.colormaps.get_cmap("rainbow").resampled(n_masks)
    colors = [
        tuple(int(c * 255) for c in cmap(i)[:3])
        for i in range(n_masks)
    ]

    for mask, color in zip(masks, colors):
        mask = Image.fromarray(mask)
        overlay = Image.new("RGBA", image.size, color + (0,))
        alpha = mask.point(lambda v: int(v * 0.5))
        overlay.putalpha(alpha)
        image = Image.alpha_composite(image, overlay)
    return image
    
def show_points(coords, labels, ax, marker_size=375):
    """
    Plot points on the image: positive points in green and negative in red.

    Parameters:
      coords (numpy.ndarray): Coordinates of the points.
      labels (numpy.ndarray): Binary labels corresponding to each point (1 for positive, 0 for negative).
      ax (matplotlib.axes.Axes): Axis to plot the points.
      marker_size (int): Size of the plotted markers.
    """
    # Separate points by label
    pos_points = coords[labels == 1]
    neg_points = coords[labels == 0]
    
    # Plot positive points (green stars) and negative points (red stars)
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*',
               s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*',
               s=marker_size, edgecolor='white', linewidth=1.25)

def show_box(box, ax):
    """
    Draw a bounding box on the given axis.

    Parameters:
      box (list or numpy.ndarray): Box coordinates in [x_min, y_min, x_max, y_max] format.
      ax (matplotlib.axes.Axes): Axis to draw the box.
    """
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    # Draw a rectangle with a green edge and transparent fill
    ax.add_patch(plt.Rectangle((x0, y0), w, h, edgecolor='green', facecolor=(0, 0, 0, 0), lw=2))
    
def generate_polygons(contours, hierarchy):
  """Generates a list of Shapely polygons from the contours hirarchy returned by cv2.find_contours().
     The list of polygons is generated by performing a depth-first search on the contours hierarchy tree.
  Parameters
  ----------
  contours : list
    The contours returned by cv2.find_contours()
  hierarchy : list
    The hierarchy returned by cv2.find_contours()
  Returns
  -------
  list
    The list of generated Shapely polygons
  """
  
  hierarchy = hierarchy[0]
  polygons = []
  _DFS(polygons, contours, hierarchy, 0, True, [])
  return polygons
  
def draw_matches(img0, img1, matchpoints0, matchpoints1, matchconf):
  alpha = 0.1
  # Create a color map for visualizing match confidence
  colors = cm.jet(matchconf)
  fig, axes = plt.subplots(1, 2, figsize=(10, 4))  # 1 row, 2 columns
  axes[0].imshow(img0)
  axes[0].scatter(matchpoints0[:, 0], matchpoints0[:, 1], marker=".", color=colors, s=5, alpha=alpha)
  axes[0].axis('off')
  axes[1].imshow(img1)
  axes[1].scatter(matchpoints1[:, 0], matchpoints1[:, 1], marker=".", color=colors, s=5, alpha=alpha)
  axes[1].axis('off')
  for i, x in enumerate(matchpoints0):
    start = (int(matchpoints0[i][0]),int(matchpoints0[i][1]))
    end = (int(matchpoints1[i][0]), int(matchpoints1[i][1]))

    con = ConnectionPatch(xyA=start, xyB=end, coordsA="data", coordsB="data",
                        axesA=axes[0], axesB=axes[1], color=colors[i], alpha=alpha)
    axes[1].add_artist(con)
  return fig
  #plt.show()

# =============================================================================
# Load Configuration from YAML File
# =============================================================================

# Open and parse the YAML configuration file.
with open("loftr_config.yaml", "r") as f:
    config = yaml.safe_load(f)

# Assign configuration parameters to variables
EXPERIMENT_NAME = config["EXPERIMENT_NAME"]
IMG0_PTH = Path(config["IMG0_PTH"])
IMG1_PTH = Path(config["IMG1_PTH"])
TEXT_PROMPT = config["TEXT_PROMPT"]
LOFTR_IMAGE_TYPE = config["LOFTR_IMAGE_TYPE"]
SAM_MODEL_CFG = config["SAM_MODEL_ID"]
DISPLAY_POINTS_INSIDE = config["DISPLAY_POINTS_INSIDE"]
LOFTR_MATCHING_NAME = config["LOFTR_MATCHING_NAME"]
RESIZE_HEIGHT = config["RESIZE_HEIGHT"]
RESIZE_WIDTH = config["RESIZE_WIDTH"]

device = "cuda" if torch.cuda.is_available() else "cpu"
    
# Create an output directory with a unique name based on the 
# experiment name as well as the current date and time.
now = datetime.now()
date = now.strftime("%Y%m%d")
time = now.strftime("%H%M")
OUTPUT_DIR = os.path.join(EXPERIMENT_NAME, date, time)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# =============================================================================
# Create a label map 
# =============================================================================
'''
labelDict = {}
text_prompt_list = TEXT_PROMPT.split(" . ")
for j, element in enumerate(text_prompt_list):
  if element not in labelDict:
    labelDict[element] = j'''
#print(labelDict)

# =============================================================================
# Load and Process the Input Image Pair using kornia
# =============================================================================

# Read the first image and resize
img0 = K.io.load_image(IMG0_PTH, K.io.ImageLoadType.RGB32)[None, ...]
img0 = K.geometry.resize(img0, (RESIZE_HEIGHT, RESIZE_WIDTH), antialias=True)

# Read the second image and resize
img1 = K.io.load_image(IMG1_PTH, K.io.ImageLoadType.RGB32)[None, ...]
img1 = K.geometry.resize(img1, (RESIZE_HEIGHT, RESIZE_WIDTH), antialias=True)


# =============================================================================
# Run LoFTR Inference and Save the Matching Figure
# =============================================================================

matcher = KF.LoFTR(pretrained=LOFTR_IMAGE_TYPE)

input_dict = {
    "image0": K.color.rgb_to_grayscale(img0),  # LofTR works on grayscale images only
    "image1": K.color.rgb_to_grayscale(img1),
}

with torch.inference_mode():
    correspondences = matcher(input_dict)

mkpts0 = correspondences["keypoints0"].cpu().numpy()
mkpts1 = correspondences["keypoints1"].cpu().numpy()
mconf = correspondences["confidence"].cpu().numpy()

# =============================================================================
# Load the Input Image Pair using pillow, and resize to same size used in LoFTR
# =============================================================================

img0_pil = Image.open(IMG0_PTH).convert("RGB")
img0_pil = img0_pil.resize((RESIZE_WIDTH, RESIZE_HEIGHT ))

img1_pil = Image.open(IMG1_PTH).convert("RGB")
img1_pil = img1_pil.resize((RESIZE_WIDTH, RESIZE_HEIGHT ))

loftrmatches = draw_matches(img0_pil, img1_pil, mkpts0, mkpts1, mconf)

matching_name = f"ALL_{LOFTR_MATCHING_NAME}_whole_image.png"

plt.savefig(os.path.join(OUTPUT_DIR, matching_name), dpi=300, bbox_inches="tight")
#plt.show()
plt.clf()

# =============================================================================
# SAM3 Mask Generation
# =============================================================================
# Load the model



model = Sam3Model.from_pretrained(SAM_MODEL_CFG).to(device)
processor = Sam3Processor.from_pretrained(SAM_MODEL_CFG)
# Load an image

#img0_np = np.array(img0_pil.convert("RGB"))
inference_state = processor.set_image(img0)

# select the device for computation
device = "cuda" if torch.cuda.is_available() else "cpu"

# Prompt the model with text
with torch.no_grad():
    outputs = model(**inputs)

# Post-process results
results = processor.post_process_instance_segmentation(
    outputs,
    threshold=0.5,
    mask_threshold=0.5,
    target_sizes=inputs.get("original_sizes").tolist()
)[0]

overlay = overlay_masks(img0, results["masks"])
plt.imshow(overlay)
plt.show()
'''
sam_masks1 = []
sam_scores1 = []

for mask in masks0:        
  # squeeze the mask to remove extra dimension, then cast to int to create a binary image and extract its contours.
  #
  flat_mask = np.squeeze(mask['segmentation']).astype('uint8')

  contours, hierarchy = cv2.findContours(flat_mask.astype('uint8'),
                                         cv2.RETR_TREE,
                                         cv2.CHAIN_APPROX_SIMPLE)
                                         

  polygons = generate_polygons(contours, hierarchy)

  if len(polygons) == 1:
      # Initialize lists to store refined matching points within the detected object.
      picture0points = []
      picture1points = []
      matchconf = []
      points1labels = []
      
      # Iterate through all LoFTR keypoints in the first image.
      for idx, point in enumerate(mkpts0):
          # Create a shapely Point from the keypoint.

          if Point(point).within(polygons):
              print(mkpts0[idx])
              # If the point lies within the detected object's polygon, store it.
              picture0points.append(mkpts0[idx])
              picture1points.append(mkpts1[idx])
              points1labels.append(1)
              matchconf.append(mconf[idx])
      print(len(picture0points))
      # Convert the collected points to numpy arrays for plotting and further processing.
      picture0points = np.array(picture0points)
      picture1points = np.array(picture1points)
      points1labels = np.array(points1labels)      
      
      if len(picture0points) > 0:
          # Save a matching figure for the detected object region.
          #object_matching_name = f"{LOFTR_MATCHING_NAME}_{phrases[i]}.pdf"
          #make_matching_figure(img0_raw, img1_raw, picture0points, picture1points,
                               #color1, picture0points, picture1points,
                               #text1, path=os.path.join(OUTPUT_DIR, object_matching_name))

          # Load and preprocess the second image (IMG1) for generating a corresponding mask.
      
          # Set the SAM2 predictor to use the processed image.

          with torch.inference_mode(), torch.autocast("cuda", dtype=torch.bfloat16):
            predictor.set_image(img1_pil)
            
            masks1, scores1, logits1 = predictor.predict(
              point_coords=picture1points,      # No initial points provided
              point_labels=points1labels,      # No initial point labels
              multimask_output=False, # Generate a single mask output
              )
            sam_masks1.append(masks1)
            sam_scores1.append(scores1[0])
            
      else:
          # If any errors occur during processing, print a warning message with details.
          print("This polygon does not appear to have any loftr matches")

      # Optionally, display the matching points along with the detected object's contour.
      if DISPLAY_POINTS_INSIDE:
          plt.figure(figsize=(10, 10))
          plt.imshow(img0_rgb)
          # Plot the original LoFTR keypoints in red.
          plt.scatter(mkpts0[:, 0], mkpts0[:, 1], marker="x", color="red", s=200)
          # Transpose the contour points for plotting.
          shape_contours_T = np.transpose(shape_contours)
          plt.scatter(shape_contours_T[0], shape_contours_T[1], marker=".", color="blue", s=200)
          plt.savefig(os.path.join(OUTPUT_DIR, "pointsInside.jpg"), dpi=300)
          plt.clf()
          #plt.show()

# =============================================================================
# Display the generated masks (using gdino bboxs and SAM2) 
# on image 0 with random colors.
# =============================================================================
plt.imshow(img0_pil)
show_anns(masks0)
#show_masks_new(img0_pil, masks)

image0_maskname = f'allobjects_localization_img0_{os.path.basename(IMG0_PTH).split(".")[0]}.jpg'
plt.axis('off')
plt.savefig(os.path.join(OUTPUT_DIR, image0_maskname), dpi=300, bbox_inches='tight')
#plt.show()
plt.clf()

# =============================================================================
# Display the generated masks (using gdino bboxs and SAM2) 
# on image 1 with random colors.
# =============================================================================

show_masks_new(img1_pil, sam_masks1, sam_scores1)

image1_maskname = f'matched_objects_img1_{os.path.basename(IMG1_PTH).split(".")[0]}.jpg'
plt.axis('off')
plt.savefig(os.path.join(OUTPUT_DIR, image1_maskname), dpi=300, bbox_inches='tight')
#plt.show()
plt.clf()'''