# config.yaml

EXPERIMENT_NAME: "CODa_ReID"
TEXT_PROMPT: "hydrant"
IMG0_PTH: "E:\\IMPACT\\data_collection\\test0\\0\\2d_rect_cam0_0_701.jpg"
IMG1_PTH: "E:\\IMPACT\\data_collection\\test0\\0\\2d_rect_cam0_0_713.jpg"
SAM_MODEL_ID: "facebook/sam3"
MATCHING_NAME: "LightGlue_matching"
RESIZE_HEIGHT: 480
RESIZE_WIDTH: 640
CREATE_SAVEDIR: False
VISUALIZE_FIG: False
Y: 3
VIT_MODEL_NAME: "openai/clip-vit-base-patch32"
NUM_PARTS: 6
A: 0.8
B: 0.15
C: 0.05